spring:
  application:
    name: demo-spring-server
  profiles:
    active: dev
server:
  port: 12380
eureka:
  instance:
    hostname: ${demo.spring.server.eureka.instance.hostname}
    appname: ${spring.application.name}
    ip-address: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
